vich_uploader:
  db_driver: orm

  mappings:
    images:
      uri_prefix: '%app_path.images%'
      upload_destination: '%kernel.project_dir%/public/%app_path.images%'
      namer: Vich\UploaderBundle\Naming\UniqidNamer