easy_admin:

  site_name: '%site_name%'

  user:
      avatar_property_path: 'image'

  list:
    batch_actions: ['delete']

  design:
    templates:
      layout: 'admin/layout.html.twig'

    menu:
      - { label: 'General' }
      - { label: Dashboard, icon: tasks, route: admin.dashboard, default: true }
      - { entity: Page, label: Pages, icon: clone }
      - { entity: User, label: Users, icon: user, role: ROLE_SUPER_ADMIN }