easy_admin:
  entities:
    User:

      class: App\Entity\User
      controller: App\Controller\Admin\UserController
      label: User

      form:
        fields:
          - 'email'
          - 'firstname'
          - 'lastname'
          - 'username'
          - { property: 'password', type: password }
          - { property: image, type: App\Form\ImageType }
          - { property: 'role', type: App\Form\RoleType, type_options: { required: true, roles : '%security.role_hierarchy.roles%' } }

      list:
        title: '<i class="fa fa-fw fa-user"></i>  Users'
        fields:
          - { property: 'email', label: 'Email' }
          - { property: 'username', label: 'Username' }
          - { property: 'firstname', label: 'Firstname' }
          - { property: 'lastname', label: 'Lastname' }
          - { property: 'role', label: 'Role' }
          - { property: 'image.imageName', label: 'Avatar', type: 'image', base_path: '%app_path.images%' }